name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:    

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3      
    - name: create
      env:
        CONFIGURATION_JSON: ${{ secrets.CONFIGURATION_JSON }}
      run: echo CONFIGURATION_JSON
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
